FROM node:12-alpine3.12
RUN \
  apk update && \
  apk  upgrade && \
  apk add bash git openssh-client wget chromium firefox-esr curl && \
  npm install --global npm@latest
ENV CHROME_BIN=/usr/bin/chromium-browser
