import { createApi, fetchBaseQuery, retry } from '@reduxjs/toolkit/query/react';
import config from '../../config';
import { keycloak } from '../../keycloak';
import { v4 as uuidv4 } from 'uuid';

import tidepoolApi from '../../core/api';

const fallbackSessionTrace = uuidv4();

const RETRY_COUNT = 1;

const getSessionTrace = () => {
  // To ensure that all requests from Blip have the same trace-session token, we inject
  // the trace-session token that is generated by `platform-client`. In the future, when
  // `platform-client` is no longer being used, we can remove this dependency and use
  // only a token generated by Blip
  return tidepoolApi?.tidepool?.getSessionTrace() || fallbackSessionTrace;
};

const baseQuery = fetchBaseQuery({
  baseUrl: `${config.API_HOST}/v1/`,
  prepareHeaders: (headers) => {
    headers.set('x-tidepool-session-token', keycloak?.token || '');
    headers.set('x-tidepool-trace-session', getSessionTrace());

    return headers;
  },
});

const baseQueryWithKeycloakErrorHandling = async (args, api, extraOptions) => {
  const result = await baseQuery(args, api, extraOptions);

  if (result.error && [401, 403].includes(result.error.status)) {
    api.dispatch({ type: 'RTK_QUERY_AUTH_ERROR', error: { status: result.error.status } });
  }

  return result;
};

export const RTKQueryApi = createApi({
  reducerPath: 'api',
  baseQuery: retry(
    baseQueryWithKeycloakErrorHandling,
    { maxRetries: RETRY_COUNT },
  ),
  endpoints: () => ({}),
});
