import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import config from '../../config';
import { keycloak } from '../../keycloak';
import { v4 as uuidv4 } from 'uuid';

import tidepoolApi from '../../core/api';

const fallbackSessionTrace = uuidv4();

const getSessionTrace = () => {
  // To ensure that all requests from Blip have the same trace-session token, we inject
  // the trace-session token that is generated by `platform-client`. In the future, when
  // `platform-client` is no longer being used, we can remove this dependency
  let sessionTrace = tidepoolApi?.tidepool?.getSessionTrace();

  if (!sessionTrace) {
    sessionTrace = fallbackSessionTrace;
  }

  return sessionTrace;
};

export const RTKQueryApi = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({
    baseUrl: `${config.API_HOST}/v1/`,
    prepareHeaders: (headers) => {
      if (keycloak?.token) {
        headers.set('x-tidepool-session-token', keycloak?.token);
      }

      headers.set('x-tidepool-trace-session', getSessionTrace());

      return headers;
    },
  }),
  endpoints: () => ({}),
});
