/*
 * == BSD2 LICENSE ==
 * Copyright (c) 2014, Tidepool Project
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the associated License, which is identical to the BSD 2-Clause
 * License as published by the Open Source Initiative at opensource.org.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the License for more details.
 *
 * You should have received a copy of the License along with this program; if
 * not, you can obtain one from Tidepool Project at tidepool.org.
 * == BSD2 LICENSE ==
 */
 
'use strict';

var timezones = [
  {label: '(UTC-05:00) Eastern Time (U.S.)', name: 'US/Eastern'},
  {label: '(UTC-06:00) Central Time (U.S.)', name: 'US/Central'},
  {label: '(UTC-07:00) Mountain Time (U.S.)', name: 'US/Mountain'},
  {label: '(UTC-08:00) Pacific Time (U.S.)', name: 'US/Pacific'},
  {label: '(UTC-11:00) Midway Island', name: 'Pacific/Midway'},
  {label: '(UTC-10:00) Hawaii', name: 'Pacific/Honolulu'},
  {label: '(UTC-08:00) Los Angeles', name: 'America/Los_Angeles'},
  {label: '(UTC-08:00) Tijuana', name: 'America/Tijuana'},
  {label: '(UTC-07:00) Phoenix', name: 'America/Phoenix'},
  {label: '(UTC-07:00) Chihuahua', name: 'America/Chihuahua'},
  {label: '(UTC-07:00) La Paz', name: 'America/Chihuahua'},
  {label: '(UTC-07:00) Mazatlan', name: 'America/Mazatlan'},
  {label: '(UTC-07:00) Denver', name: 'America/Denver'},
  {label: '(UTC-06:00) Central America', name: 'America/Managua'},
  {label: '(UTC-06:00) Chicago', name: 'America/Chicago'},
  {label: '(UTC-06:00) Guadalajara', name: 'America/Mexico_City'},
  {label: '(UTC-06:00) Mexico City', name: 'America/Mexico_City'},
  {label: '(UTC-06:00) Monterrey', name: 'America/Monterrey'},
  {label: '(UTC-05:00) Bogota', name: 'America/Bogota'},
  {label: '(UTC-05:00) New York', name: 'America/New_York'},
  {label: '(UTC-05:00) Indianapolis', name: 'America/Indiana/Indianapolis'},
  {label: '(UTC-05:00) Lima', name: 'America/Lima'},
  {label: '(UTC-05:00) Quito', name: 'America/Bogota'},
  {label: '(UTC-04:30) Caracas', name: 'America/Caracas'},
  {label: '(UTC-04:00) La Paz', name: 'America/La_Paz'},
  {label: '(UTC-04:00) Santiago', name: 'America/Santiago'},
  {label: '(UTC-03:00) Brasilia', name: 'America/Sao_Paulo'},
  {label: '(UTC-03:00) Buenos Aires', name: 'America/Argentina/Buenos_Aires'},
  {label: '(UTC-03:00) Georgetown', name: 'America/Argentina/Buenos_Aires'},
  {label: '(UTC-03:00) Greenland', name: 'America/Godthab'},
  {label: '(UTC-02:00) Mid-Atlantic', name: 'America/Noronha'},
  {label: '(UTC-01:00) Azores', name: 'Atlantic/Azores'},
  {label: '(UTC-01:00) Cape Verde Is.', name: 'Atlantic/Cape_Verde'},
  {label: '(UTC+00:00) Casablanca', name: 'Africa/Casablanca'},
  {label: '(UTC+00:00) Edinburgh', name: 'Europe/London'},
  {label: '(UTC+00:00) Greenwich Mean Time : Dublin', name: 'Etc/Greenwich'},
  {label: '(UTC+00:00) Lisbon', name: 'Europe/Lisbon'},
  {label: '(UTC+00:00) London', name: 'Europe/London'},
  {label: '(UTC+00:00) Monrovia', name: 'Africa/Monrovia'},
  {label: '(UTC+01:00) Amsterdam', name: 'Europe/Amsterdam'},
  {label: '(UTC+01:00) Belgrade', name: 'Europe/Belgrade'},
  {label: '(UTC+01:00) Berlin', name: 'Europe/Berlin'},
  {label: '(UTC+01:00) Bern', name: 'Europe/Berlin'},
  {label: '(UTC+01:00) Bratislava', name: 'Europe/Bratislava'},
  {label: '(UTC+01:00) Brussels', name: 'Europe/Brussels'},
  {label: '(UTC+01:00) Budapest', name: 'Europe/Budapest'},
  {label: '(UTC+01:00) Copenhagen', name: 'Europe/Copenhagen'},
  {label: '(UTC+01:00) Ljubljana', name: 'Europe/Ljubljana'},
  {label: '(UTC+01:00) Madrid', name: 'Europe/Madrid'},
  {label: '(UTC+01:00) Paris', name: 'Europe/Paris'},
  {label: '(UTC+01:00) Prague', name: 'Europe/Prague'},
  {label: '(UTC+01:00) Rome', name: 'Europe/Rome'},
  {label: '(UTC+01:00) Sarajevo', name: 'Europe/Sarajevo'},
  {label: '(UTC+01:00) Skopje', name: 'Europe/Skopje'},
  {label: '(UTC+01:00) Stockholm', name: 'Europe/Stockholm'},
  {label: '(UTC+01:00) Vienna', name: 'Europe/Vienna'},
  {label: '(UTC+01:00) Warsaw', name: 'Europe/Warsaw'},
  {label: '(UTC+01:00) West Central Africa', name: 'Africa/Lagos'},
  {label: '(UTC+01:00) Zagreb', name: 'Europe/Zagreb'},
  {label: '(UTC+02:00) Athens', name: 'Europe/Athens'},
  {label: '(UTC+02:00) Bucharest', name: 'Europe/Bucharest'},
  {label: '(UTC+02:00) Cairo', name: 'Africa/Cairo'},
  {label: '(UTC+02:00) Harare', name: 'Africa/Harare'},
  {label: '(UTC+02:00) Helsinki', name: 'Europe/Helsinki'},
  {label: '(UTC+02:00) Istanbul', name: 'Europe/Istanbul'},
  {label: '(UTC+02:00) Jerusalem', name: 'Asia/Jerusalem'},
  {label: '(UTC+02:00) Kyiv', name: 'Europe/Helsinki'},
  {label: '(UTC+02:00) Pretoria', name: 'Africa/Johannesburg'},
  {label: '(UTC+02:00) Riga', name: 'Europe/Riga'},
  {label: '(UTC+02:00) Sofia', name: 'Europe/Sofia'},
  {label: '(UTC+02:00) Tallinn', name: 'Europe/Tallinn'},
  {label: '(UTC+02:00) Vilnius', name: 'Europe/Vilnius'},
  {label: '(UTC+03:00) Baghdad', name: 'Asia/Baghdad'},
  {label: '(UTC+03:00) Kuwait', name: 'Asia/Kuwait'},
  {label: '(UTC+03:00) Minsk', name: 'Europe/Minsk'},
  {label: '(UTC+03:00) Nairobi', name: 'Africa/Nairobi'},
  {label: '(UTC+03:00) Riyadh', name: 'Asia/Riyadh'},
  {label: '(UTC+03:00) Volgograd', name: 'Europe/Volgograd'},
  {label: '(UTC+03:30) Tehran', name: 'Asia/Tehran'},
  {label: '(UTC+04:00) Abu Dhabi', name: 'Asia/Muscat'},
  {label: '(UTC+04:00) Baku', name: 'Asia/Baku'},
  {label: '(UTC+04:00) Moscow', name: 'Europe/Moscow'},
  {label: '(UTC+04:00) Muscat', name: 'Asia/Muscat'},
  {label: '(UTC+04:00) St. Petersburg', name: 'Europe/Moscow'},
  {label: '(UTC+04:00) Tbilisi', name: 'Asia/Tbilisi'},
  {label: '(UTC+04:00) Yerevan', name: 'Asia/Yerevan'},
  {label: '(UTC+04:30) Kabul', name: 'Asia/Kabul'},
  {label: '(UTC+05:00) Islamabad', name: 'Asia/Karachi'},
  {label: '(UTC+05:00) Karachi', name: 'Asia/Karachi'},
  {label: '(UTC+05:00) Tashkent', name: 'Asia/Tashkent'},
  {label: '(UTC+05:30) Kolkata', name: 'Asia/Kolkata'},
  {label: '(UTC+05:45) Kathmandu', name: 'Asia/Kathmandu'},
  {label: '(UTC+06:00) Almaty', name: 'Asia/Almaty'},
  {label: '(UTC+06:00) Astana', name: 'Asia/Dhaka'},
  {label: '(UTC+06:00) Dhaka', name: 'Asia/Dhaka'},
  {label: '(UTC+06:00) Ekaterinburg', name: 'Asia/Yekaterinburg'},
  {label: '(UTC+06:30) Rangoon', name: 'Asia/Rangoon'},
  {label: '(UTC+07:00) Bangkok', name: 'Asia/Bangkok'},
  {label: '(UTC+07:00) Hanoi', name: 'Asia/Bangkok'},
  {label: '(UTC+07:00) Jakarta', name: 'Asia/Jakarta'},
  {label: '(UTC+07:00) Novosibirsk', name: 'Asia/Novosibirsk'},
  {label: '(UTC+08:00) Beijing', name: 'Asia/Hong_Kong'},
  {label: '(UTC+08:00) Chongqing', name: 'Asia/Chongqing'},
  {label: '(UTC+08:00) Hong Kong', name: 'Asia/Hong_Kong'},
  {label: '(UTC+08:00) Krasnoyarsk', name: 'Asia/Krasnoyarsk'},
  {label: '(UTC+08:00) Kuala Lumpur', name: 'Asia/Kuala_Lumpur'},
  {label: '(UTC+08:00) Perth', name: 'Australia/Perth'},
  {label: '(UTC+08:00) Singapore', name: 'Asia/Singapore'},
  {label: '(UTC+08:00) Taipei', name: 'Asia/Taipei'},
  {label: '(UTC+08:00) Urumqi', name: 'Asia/Urumqi'},
  {label: '(UTC+09:00) Irkutsk', name: 'Asia/Irkutsk'},
  {label: '(UTC+09:00) Osaka', name: 'Asia/Tokyo'},
  {label: '(UTC+09:00) Sapporo', name: 'Asia/Tokyo'},
  {label: '(UTC+09:00) Seoul', name: 'Asia/Seoul'},
  {label: '(UTC+09:00) Tokyo', name: 'Asia/Tokyo'},
  {label: '(UTC+09:30) Adelaide', name: 'Australia/Adelaide'},
  {label: '(UTC+09:30) Darwin', name: 'Australia/Darwin'},
  {label: '(UTC+10:00) Brisbane', name: 'Australia/Brisbane'},
  {label: '(UTC+10:00) Guam', name: 'Pacific/Guam'},
  {label: '(UTC+10:00) Hobart', name: 'Australia/Hobart'},
  {label: '(UTC+10:00) Melbourne', name: 'Australia/Melbourne'},
  {label: '(UTC+10:00) Port Moresby', name: 'Pacific/Port_Moresby'},
  {label: '(UTC+10:00) Sydney', name: 'Australia/Sydney'},
  {label: '(UTC+10:00) Yakutsk', name: 'Asia/Yakutsk'},
  {label: '(UTC+11:00) Vladivostok', name: 'Asia/Vladivostok'},
  {label: '(UTC+12:00) Auckland', name: 'Pacific/Auckland'},
  {label: '(UTC+12:00) Fiji', name: 'Pacific/Fiji'},
  {label: '(UTC+12:00) International Date Line West', name: 'Pacific/Kwajalein'},
  {label: '(UTC+12:00) Kamchatka', name: 'Asia/Kamchatka'},
  {label: '(UTC+12:00) Magadan', name: 'Asia/Magadan'},
  {label: '(UTC+12:00) Marshall Is.', name: 'Pacific/Fiji'},
  {label: '(UTC+12:00) New Caledonia', name: 'Asia/Magadan'},
  {label: '(UTC+12:00) Solomon Is.', name: 'Asia/Magadan'},
  {label: '(UTC+12:00) Wellington', name: 'Pacific/Auckland'},
  {label: '(UTC+13:00) Nuku\'alofa', name: 'Pacific/Tongatapu'}
];

module.exports = timezones;
