import * as types from './actionTypes';

export default (type) => {
  switch (type) {
    case types.FETCH_USER_REQUEST:
    case types.FETCH_USER_SUCCESS:
    case types.FETCH_USER_FAILURE:
      return 'fetchingUser';
    case types.FETCH_PENDING_INVITES_REQUEST:
    case types.FETCH_PENDING_INVITES_SUCCESS:
    case types.FETCH_PENDING_INVITES_FAILURE:
      return 'fetchingPendingInvites';
    case types.FETCH_PENDING_MEMBERSHIPS_REQUEST:
    case types.FETCH_PENDING_MEMBERSHIPS_SUCCESS:
    case types.FETCH_PENDING_MEMBERSHIPS_FAILURE:
      return 'fetchingPendingMemberships';
    case types.FETCH_PATIENTS_REQUEST:
    case types.FETCH_PATIENTS_SUCCESS:
    case types.FETCH_PATIENTS_FAILURE:
      return 'fetchingPatients';
    case types.FETCH_PATIENT_REQUEST:
    case types.FETCH_PATIENT_SUCCESS:
    case types.FETCH_PATIENT_FAILURE:
      return 'fetchingPatient';
    case types.FETCH_PATIENT_DATA_REQUEST:
    case types.FETCH_PATIENT_DATA_SUCCESS:
    case types.FETCH_PATIENT_DATA_FAILURE:
      return 'fetchingPatientData';
    case types.FETCH_MESSAGE_THREAD_REQUEST:
    case types.FETCH_MESSAGE_THREAD_SUCCESS:
    case types.FETCH_MESSAGE_THREAD_FAILURE:
      return 'fetchingMessageThread';
    case types.LOGIN_REQUEST:
    case types.LOGIN_SUCCESS:
    case types.LOGIN_FAILURE:
      return 'loggingIn';
    case types.LOGOUT_REQUEST:
    case types.LOGOUT_SUCCESS:
    case types.LOGOUT_FAILURE:
      return 'loggingOut';
    case types.SIGNUP_REQUEST:
    case types.SIGNUP_SUCCESS:
    case types.SIGNUP_FAILURE:
      return 'signingUp';
    case types.CONFIRM_SIGNUP_REQUEST:
    case types.CONFIRM_SIGNUP_SUCCESS:
    case types.CONFIRM_SIGNUP_FAILURE:
      return 'confirmingSignup';
    case types.CONFIRM_PASSWORD_RESET_REQUEST:
    case types.CONFIRM_PASSWORD_RESET_SUCCESS:
    case types.CONFIRM_PASSWORD_RESET_FAILURE:
      return 'confirmingPasswordReset';
    case types.ACCEPT_TERMS_REQUEST:
    case types.ACCEPT_TERMS_SUCCESS:
    case types.ACCEPT_TERMS_FAILURE:
      return 'acceptingTerms';
    case types.RESEND_EMAIL_VERIFICATION_REQUEST:
    case types.RESEND_EMAIL_VERIFICATION_SUCCESS:
    case types.RESEND_EMAIL_VERIFICATION_FAILURE:
      return 'resendingEmailVerification';
    case types.CREATE_PATIENT_REQUEST:
    case types.CREATE_PATIENT_SUCCESS:
    case types.CREATE_PATIENT_FAILURE:
      return 'creatingPatient';
    case types.REMOVE_PATIENT_REQUEST:
    case types.REMOVE_PATIENT_SUCCESS:
    case types.REMOVE_PATIENT_FAILURE:
      return 'removingPatient';
    case types.REMOVE_MEMBER_REQUEST:
    case types.REMOVE_MEMBER_SUCCESS:
    case types.REMOVE_MEMBER_FAILURE:
      return 'removingMember';
    case types.REQUEST_PASSWORD_RESET_REQUEST:
    case types.REQUEST_PASSWORD_RESET_SUCCESS:
    case types.REQUEST_PASSWORD_RESET_FAILURE:
      return 'requestingPasswordReset';
    case types.SEND_INVITATION_REQUEST:
    case types.SEND_INVITATION_SUCCESS:
    case types.SEND_INVITATION_FAILURE:
      return 'sendingInvitation';
    case types.CANCEL_INVITATION_REQUEST:
    case types.CANCEL_INVITATION_SUCCESS:
    case types.CANCEL_INVITATION_FAILURE:
      return 'cancellingInvitation';
    case types.ACCEPT_MEMBERSHIP_REQUEST:
    case types.ACCEPT_MEMBERSHIP_SUCCESS:
    case types.ACCEPT_MEMBERSHIP_FAILURE:
      return 'acceptingMembership';
    case types.DISMISS_MEMBERSHIP_REQUEST:
    case types.DISMISS_MEMBERSHIP_SUCCESS:
    case types.DISMISS_MEMBERSHIP_FAILURE:
      return 'dismissingMembership';
    case types.SET_MEMBER_PERMISSIONS_REQUEST:
    case types.SET_MEMBER_PERMISSIONS_SUCCESS:
    case types.SET_MEMBER_PERMISSIONS_FAILURE:
      return 'settingMemberPermissions';
    case types.UPDATE_PATIENT_REQUEST:
    case types.UPDATE_PATIENT_SUCCESS:
    case types.UPDATE_PATIENT_FAILURE:
      return 'updatingPatient';
    case types.UPDATE_USER_REQUEST:
    case types.UPDATE_USER_SUCCESS:
    case types.UPDATE_USER_FAILURE:
      return 'updatingUser';
    default:
      return null;
  }
};